name: Build ES 1.2 ACS image

on:
  push:
    branches:                # trigger on push to master
      - main
  pull_request:              # trigger on pull requests to master
    branches:
      - main
  schedule:
    - cron: '30 17 * * *'    # Runs everyday at 11 PM IST (17:30 UTC)

jobs:
  build_image:
    name: Build ES 1.2 ACS image
    runs-on: ubuntu-22.04
    strategy:
      matrix:
        env:
        - ARCH: x86_64
    steps:
    - name: Maximize build space
      uses: easimon/maximize-build-space@master
      with:
        remove-dotnet: 'true'
        remove-android: 'true'
        remove-haskell: 'true'
        remove-codeql: 'true'
        remove-docker-images: 'true'
    - uses: actions/checkout@v3
      with:
        fetch-depth: 1
    - name: Start building
      run:
        sudo -s;
        git config --global user.name "arm-systemready";
        git config --global user.email "arm-systemready@arm.com";
        cd ES/scripts;
        ./build-scripts/get_source.sh;
        ./build-scripts/build-es-live-image.sh
    - uses: actions/upload-artifact@v3
      with:
        name: es_acs_live_image.img.xz
        path: ES/scripts/output/es_acs_live_image.img.xz
        if-no-files-found: error

