name: Build SR 2.0 ACS image

on: [push, pull_request]

jobs:
  build_image:
    name: Build SR 2.0 ACS image
    runs-on: ubuntu-22.04
    strategy:
      matrix:
        env:
        - ARCH: x86_64
    steps:
    - name: Maximize build space
      uses: easimon/maximize-build-space@master
      with:
        remove-dotnet: 'true'
        remove-android: 'true'
        remove-haskell: 'true'
        remove-codeql: 'true'
        remove-docker-images: 'true'
    - uses: actions/checkout@v3
      with:
        fetch-depth: 1
    - name: Start building
      run:
        sudo -s;
        git config --global user.name "arm-systemready";
        git config --global user.email "arm-systemready@arm.com";
        cd SR/scripts;
        ./build-scripts/get_source.sh;
        ./build-scripts/build-sr-live-image.sh
    - uses: actions/upload-artifact@v3
      with:
        name: sr_acs_live_image.img.xz
        path: SR/scripts/output/sr_acs_live_image.img.xz
        if-no-files-found: error

