name: SystemReady Bands Daily Builds

on:
  schedule:
    - cron: '30 17 * * *'    # Runs everyday at 11 PM IST
  workflow_dispatch:         # to dispatch from Github Actions

jobs:
  ES_Build:
    name: ES ACS Daily Build Image
    runs-on: ubuntu-22.04
    strategy:
      matrix:
        env:
        - ARCH: x86_64
    steps:
    - name: Maximize build space
      uses: easimon/maximize-build-space@master
      with:
        remove-dotnet: 'true'
        remove-android: 'true'
        remove-haskell: 'true'
        remove-codeql: 'true'
        remove-docker-images: 'true'
    - uses: actions/checkout@v4
      with:
        fetch-depth: 1
    - name: Start building
      run:
        sudo -s;
        git config --global user.name "arm-systemready";
        git config --global user.email "arm-systemready@arm.com";
        cd ES/scripts;
        ./build-scripts/get_source.sh;
        ./build-scripts/build-es-live-image.sh
    - uses: actions/upload-artifact@v4
      with:
        name: es_acs_live_image.img.xz
        path: ES/scripts/output/es_acs_live_image.img.xz
        if-no-files-found: error
        
  SR_Build:
    name: SR ACS Daily Build Image
    runs-on: ubuntu-22.04
    strategy:
      matrix:
        env:
        - ARCH: x86_64
    steps:
    - name: Maximize build space
      uses: easimon/maximize-build-space@master
      with:
        remove-dotnet: 'true'
        remove-android: 'true'
        remove-haskell: 'true'
        remove-codeql: 'true'
        remove-docker-images: 'true'
    - uses: actions/checkout@v4
      with:
        fetch-depth: 1
    - name: Start building
      run:
        sudo -s;
        git config --global user.name "arm-systemready";
        git config --global user.email "arm-systemready@arm.com";
        cd SR/scripts;
        ./build-scripts/get_source.sh;
        ./build-scripts/build-sr-live-image.sh
    - uses: actions/upload-artifact@v4
      with:
        name: sr_acs_live_image.img.xz
        path: SR/scripts/output/sr_acs_live_image.img.xz
        if-no-files-found: error
  
  IR_Build:
    name: IR ACS Daily Build Image
    runs-on: ubuntu-22.04
    strategy:
      matrix:
        env:
        - ARCH: x86_64
    steps:
    - name: Maximize build space
      uses: easimon/maximize-build-space@master
      with:
        remove-dotnet: 'true'
        remove-android: 'true'
        remove-haskell: 'true'
        remove-codeql: 'true'
        remove-docker-images: 'true'
    - uses: actions/checkout@v4
      with:
        fetch-depth: 1
    - name: Start building
      run:
        sudo -s;
        git config --global user.name "arm-systemready";
        git config --global user.email "arm-systemready@arm.com";
        cd IR/Yocto;
        ./build-scripts/get_source.sh;
        sed -i 's/if 0 == os.getuid/if 1 == os.getuid/' meta-woden/poky/meta/classes-global/sanity.bbclass;
        ./build-scripts/build-ir-live-image.sh
    - uses: actions/upload-artifact@v4
      with:
        name: ir-acs-live-image-generic-arm64.wic.xz
        path: IR/Yocto/meta-woden/build/tmp/deploy/images/generic-arm64/ir-acs-live-image-generic-arm64.wic.xz
        if-no-files-found: error
