name: SystemReady band Build Checker

on:
  push:
    branches:                # trigger on push to master
      - main
  pull_request:              # trigger on pull requests to master
    branches:
      - main
  workflow_dispatch:         # to dispatch from Github Actions

jobs:
  build_image:
    name: SystemReady band Build Check
    runs-on: ubuntu-22.04
    strategy:
      matrix:
        env:
        - ARCH: x86_64
    steps:
    - name: Maximize build space
      uses: easimon/maximize-build-space@master
      with:
        remove-dotnet: 'true'
        remove-android: 'true'
        remove-haskell: 'true'
        remove-codeql: 'true'
        remove-docker-images: 'true'
    - uses: actions/checkout@v3
      with:
        fetch-depth: 1
    - name: Start building
      run:
        sudo -s;
        git config --global user.name "arm-systemready";
        git config --global user.email "arm-systemready@arm.com";
        cd SystemReady-band;
        ./build-scripts/get_source.sh;
        ./build-scripts/build-systemready-band-live-image.sh
    - uses: actions/upload-artifact@v3
      with:
        name: systemready_acs_live_image.img.xz
        path: SystemReady-band/output/systemready_acs_live_image.img.xz
        if-no-files-found: error

