name: SystemReady Bands Daily Builds

on:
  schedule:
    - cron: '30 17 * * *'    # Runs everyday at 11 PM IST
  workflow_dispatch:         # to dispatch from Github Actions

jobs:
  SystemReady_Build:
    name: SystemReady band Daily Build Image
    runs-on: ubuntu-22.04
    strategy:
      matrix:
        env:
        - ARCH: x86_64
    steps:
    - name: Maximize build space
      uses: easimon/maximize-build-space@master
      with:
        remove-dotnet: 'true'
        remove-android: 'true'
        remove-haskell: 'true'
        remove-codeql: 'true'
        remove-docker-images: 'true'
    - uses: actions/checkout@v4
      with:
        fetch-depth: 1
    - name: Start building
      run:
        sudo -s;
        git config --global user.name "arm-systemready";
        git config --global user.email "arm-systemready@arm.com";
        cd SystemReady/;
        ./build-scripts/get_source.sh;
        ./build-scripts/build-systemready-live-image.sh
    - uses: actions/upload-artifact@v4
      with:
        name: systemready_acs_live_image.img.xz
        path: SystemReady-band/scripts/output/systemready_acs_live_image.img.xz
        if-no-files-found: error
